routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register'    => false]);
Route::middleware('auth')->group(function () {
    // Home
    Route::get('/', 'HomeController@index')->name('home');
    // Users
    Route::namespace('User')->group(function (){
        Route::get('psw','PswController@edit')->name('psw.edit');
        Route::put('psw','PswController@update')->name('psw.update');

        Route::resource('staff','StaffController')->except(['show']);
        Route::patch('staff/{staff}/restore', 'StaffController@restore')
            ->name('staff.restore');
    });
    // Payment
    Route::namespace('Payment')->group(function (){
        // Claim
        Route::resource('provider/{provider}/claim','ClaimController')->except(['show', "edit", "update"]);
        // Debt
        Route::resource('client/{client}/debt','DebtController')->except(['destroy', 'show']);
    });
    // Provider
    Route::namespace('Provider')->group(function (){
        Route::get('provider/links',"ProviderController@links")->name("provider.links");
        Route::resource('provider',"ProviderController")->except(['destroy']);
    });
    // Client
    Route::namespace('Client')->group(function (){
        // crud Client && searches
        Route::get('client/links',"ClientController@links")->name("client.links");
        Route::get('client/all',"ClientController@all")->name('client.all');
        Route::post('client/search/city',"ClientController@searchCity")->name('client.search.city');
        Route::post('client/search/name',"ClientController@searchName")->name('client.search.name');
        Route::resource('client',"ClientController")->except(['destroy']);
    });
    // intermediate
    Route::namespace('Intermediate')->group(function (){
        Route::resource('intermediate','IntermediateController')
            ->except(['destroy', 'show']);
    });
    // saisie
    Route::get('saisie',function (){
        return view('saisie.links');
    })->name('saisie');
    //truck
    Route::namespace('Truck')->group(function (){
        // truck
        Route::resource('truck',"TruckController")->except(['destroy']);
        // charge
        Route::resource('charge','ChargeController')->only(['create', "store"]);
        // loading
        Route::resource('loading','LoadingController')->except(['destroy', "show"]);
        // unloading
        Route::resource('unloading','UnloadingController')->except(['destroy', "show"]);
        // distributeur Links
        Route::get('distributeur', function () {
            return view('distributeur.links');
        })->name('distributeur.links');
    });
    // Trade
    Route::namespace('Trade')->group(function (){
        // BC
        Route::resource('bc','BcController')->except(['destroy']);
        // BL
        Route::resource('bl',"BlController");
        // Buy && Sale
        Route::resource('trade','TradeController')->only(['create', 'store']);
    });

    // Product
    Route::namespace('Product')->group(function (){
        Route::resource('price','PricesController')->only(['create', 'store']);
        Route::get('discount',"DiscountController@client")->name("discount.client");
        Route::resource('client/{client}/discount','DiscountController')->only(['create', 'store']);
    });



    // todo :: Debt Client, a_term
    // todo :: Claim Provider, a_term
    // todo:: Notification page
    // todo:: Factures liste imprimé recherche => 12

    // todo:: code barre 3d
    // todo :: Accounts  => 13

    // todo:: request and authorize => 14

    // todo :: GPS => 15
    // todo :: server => 16

});

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    protected $fillable = [
        "provider", "account", "name", "speaker", "rc", "patent", "ice", "creator_id"
    ];

    public function incrementProvider()
    {
        $provider = $this->whereProvider(1)->latest()->first();
        if($provider){
            return $provider->account + 100;
        }
        return 900000;
    }

    public function incrementClient()
    {
        $client = $this->whereProvider(0)->latest()->first();
        if($client){
            return $client->account + 1;
        }
        return 100000;
    }

    public function getTurnoverAttribute()
    {
        if(isset($this->trades[0])) {
            return $this->trades()->sum('ttc');
        }
        return '0.00';
    }

    public function getSoldAttribute()
    {
        return 0 . " MAD";
    }

    public function creator()
    {
        return $this->belongsTo(User::class,'creator_id');
    }

    public function stock()
    {
        return $this->hasMany(Stock::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    public function discounts()
    {
        return $this->hasMany(Discount::class);
    }

    public function trades()
    {
        return $this->hasMany(Trade::class);
    }

    public function address()
    {
        return $this->hasOne(Address::class,'client_id');
    }

    public function loadings()
    {
        return $this->hasMany(Loading::class);
    }

    public function unloadings()
    {
        return $this->hasMany(Unloading::class,'creator_id');
    }

    public function claims()
    {
        return $this->hasMany(Claim::class,"provider_id");
    }

    public function onCreateProvider(array $data,Product $product)
    {
        $provider = $this->create([
            "provider"      => 1,
            "account"       => $this->incrementProvider(),
            "name"          => $data['name'],
            "speaker"       => $data['speaker'],
            "rc"            => $data['rc'],
            "patent"        => $data['patent'],
            "ice"           => $data['ice'],
            "creator_id"    => auth()->id()
        ]);

        $product->onCreate($provider);
    }

    public function onCreateClient(array $data)
    {
        $client = $this->create([
            "provider"      => 0,
            "account"       => $this->incrementClient(),
            "name"          => $data['name'],
            "speaker"       => $data['speaker'],
            "rc"            => $data['rc'],
            "patent"        => $data['patent'],
            "ice"           => $data['ice'],
            "creator_id"    => auth()->id()
        ]);
        // address
        $client->address()->create([
            'address'   => $data['address'],
            'city_id'   => $data['city']
        ]);
        // Discount
        $products = Product::where('name','Gaz')->get();
        foreach ($products as $product) {
            $product->discounts()->create([
                "price"         => 0,
                "partner_id"    => $client->id
            ]);
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'name', 'password', "staff_id"
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $dates = [
        'created_at', "updated_at"
    ];

    public function getIsAdminAttribute()
    {
        return $this->staff->category->category === "Gérant";
    }

    public function staff()
    {
        return $this->belongsTo(Staff::class,'staff_id');
    }

    /**
     * Les Produits que j'ai ajouté
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function createdProducts()
    {
        return $this->hasMany(Product::class,'creator_id');
    }

    /**
     * Les Prix que j'ai ajouté
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productPrices()
    {
        return $this->hasMany(Price::class,'creator_id');
    }

    /**
     * La liste de tous les Camions Transporteurs et distributeurs
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function trucks()
    {
        return $this->hasMany(Truck::class,'creator_id');
    }

    public function partners()
    {
        return $this->hasMany(Partner::class,'creator_id');
    }

    public function staffs()
    {
        return $this->hasMany(Staff::class,'creator_id');
    }

    public function chargeTrucks()
    {
        return $this->hasMany(ChargeTruck::class);
    }

    public function chargeStores()
    {
        return $this->hasMany(ChargeStore::class,'creator_id');
    }

    public function trades()
    {
        return $this->hasMany(Trade::class,'creator_id');
    }

    public function loadings()
    {
        return $this->hasMany(Loading::class,'creator_id');
    }

    public function unloadings()
    {
        return $this->hasMany(Unloading::class,'creator_id');
    }


}

app/Http/Controllers/Provider/ProviderController.php
<?php

namespace App\Http\Controllers\Provider;

use App\Http\Controllers\Controller;
use App\Http\Requests\Provider\ProviderRequest;
use App\Partner;
use App\Price;
use App\Product;
use Illuminate\Http\Request;

class ProviderController extends Controller
{

    public function links()
    {
        return view('provider.links');
    }

    public function index()
    {
        $providers = Partner::whereProvider('1')
            ->orWhere('provider',3)
            ->get();
        return view('provider.index',compact('providers'));
    }

    public function create()
    {
        return view('provider.create');
    }

    public function store(ProviderRequest $request,Product $product,Partner $partner)
    {
        $partner->onCreateProvider($request->all([
            "provider", "account", "name", "speaker", "rc", "patent", "ice"
        ]),$product);
        // TODO:: notification prices products
        session()->flash('success', "Un nouveau Fournisseur a bien été Ajouté");
        return redirect()->route('provider.index');
    }

    public function show(Partner $provider,Price $price)
    {
        $products = [];
        if(isset($provider->stock[0])){
            $products["total"] = 0;
            foreach ($provider->stock as $stock) {
                $consign = $stock->product;
                $ttc = $price->getPriceRemplie($consign,$stock);
                $qt = $stock->qt;
                $size = $consign->bottle_size;
                $products[$size] = ['ttc' => $ttc, 'qt' => $qt];
                $products['total'] = $products['total'] + $ttc;
            }
        }
        // todo:: list of trades
        return view('provider.show',compact('provider','products'));
    }

    public function edit(Partner $provider)
    {
        return view('provider.edit', compact('provider'));
    }

    public function update(ProviderRequest $request,Partner $provider,Product $product)
    {
        if ($request->name != $provider->name){
            $product->onUpdateProvider($provider,$request->name);
        }
        $provider->update($request->all(["name", "speaker", "rc", "patent", "ice"]));
        session()->flash('success', "Les informations du Fournisseur ont bien été mis à jour");
        return redirect()->route('provider.show',compact('provider'));
    }

}

resources/views/provider/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                    <div class="card-header">Créer un nouveau Fournisseur</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('provider.store') }}">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Raison Social</label>
                                        <input type="text" name="name" id="name"
                                               value="{{ old('name') }}" placeholder="Raison Social"
                                               class="form-control" required>
                                        @if($errors->has('name'))
                                            <span class="text-danger">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="speaker">Nom du Gérant :</label>
                                        <input type="text" name="speaker" id="speaker" value="{{ old('speaker') }}"
                                               placeholder="Nom :" class="form-control" required>
                                        @if($errors->has('speaker'))
                                            <span class="text-danger">{{ $errors->first('speaker') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="rc">Rc :</label>
                                        <input type="text" name="rc" id="rc" value="{{ old('rc') }}" placeholder="Rc :"
                                               class="form-control" required>
                                        @if($errors->has('rc'))
                                            <span class="text-danger">{{ $errors->first('rc') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="patent">N° de patente</label>
                                        <input type="text" name="patent" id="patent" value="{{ old('patent') }}"
                                               placeholder="N° de patente" class="form-control" required>
                                        @if($errors->has('patent'))
                                            <span class="text-danger">{{ $errors->first('patent') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="ice">ICE :</label>
                                        <input type="text" name="ice" id="ice" value="{{ old('ice') }}"
                                               placeholder="ICE :" class="form-control" required>
                                        @if($errors->has('ice'))
                                            <span class="text-danger">{{ $errors->first('ice') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" name="Créer" id="Create" value="Créer"
                                           class="btn btn-primary float-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/provider/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                    <div class="card-header">Mettre à jour Le Fournisseur</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('provider.update',compact('provider')) }}">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Raison Social</label>
                                        <input type="text" name="name" id="name"
                                               value="{{ (old('name')) ?? $provider->name }}" placeholder="Raison Social"
                                               class="form-control" required>
                                        @if($errors->has('name'))
                                            <span class="text-danger">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="speaker">Nom du Gérant :</label>
                                        <input type="text" name="speaker" id="speaker"
                                               value="{{ (old('speaker')) ?? $provider->speaker }}"
                                               placeholder="Nom :" class="form-control" required>
                                        @if($errors->has('speaker'))
                                            <span class="text-danger">{{ $errors->first('speaker') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="rc">Rc :</label>
                                        <input type="text" name="rc" id="rc" value="{{ (old('rc')) ?? $provider->rc }}" placeholder="Rc :"
                                               class="form-control" required>
                                        @if($errors->has('rc'))
                                            <span class="text-danger">{{ $errors->first('rc') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="patent">N° de patente</label>
                                        <input type="text" name="patent" id="patent" value="{{ (old('patent')) ?? $provider->patent }}"
                                               placeholder="N° de patente" class="form-control" required>
                                        @if($errors->has('patent'))
                                            <span class="text-danger">{{ $errors->first('patent') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="ice">ICE :</label>
                                        <input type="text" name="ice" id="ice" value="{{ (old('ice')) ?? $provider->ice }}"
                                               placeholder="ICE :" class="form-control" required>
                                        @if($errors->has('ice'))
                                            <span class="text-danger">{{ $errors->first('ice') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" name="Créer" id="Create" value="Mettre à jour"
                                           class="btn btn-primary float-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/provider/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row mb-5">
            @if(auth()->user()->is_admin)
                <div class="col-md-12">
                    <div class="float-right">
                        <a href="{{ route('provider.create') }}"
                           class="btn btn-success text-right"
                        >Ajouter Une nouveau Fournisseur</a>
                    </div>
                </div>
            @endif
        </div>
        <div style="max-width:600px;text-align:left">
            <table id="example" class="display dataTables_wrapper" style="width:100%;">
                <thead>
                <tr>
                    <th class="text-left">Compte</th>
                    <th class="text-left">Fournisseur</th>
                    <th class="text-left">Gérant</th>
                    <th>Chiffre d'affaire</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if(isset($providers[0]))
                    @foreach($providers as $provider)
                        <tr>
                            <td class="text-left">{{ $provider->account }}</td>
                            <td class="text-left">{{ $provider->name }}</td>
                            <td class="text-left">{{ $provider->speaker }}</td>
                            <td>{{ $provider->turnover }} MAD</td>
                            <td>
                                <a href="{{ route('provider.show',compact('provider')) }}"
                                   class="btn btn-success btn-sm"> <i class="fas fa-eye"></i> Compte de Fournisseur</a>
                            </td>
                            <td>
                                <a href="{{ route('claim.index',compact('provider')) }}"
                                   class="btn btn-success btn-sm"> <i class="fas fa-eye"></i> Liste des Paiements Créances</a>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="4" class="text-center">Pas de Fournisseur pour Le moment Veuillez Ajouté un nouveau</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/provider/links.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page_links">
            <div class="row">
                <div class="col-md-4">
                    <a href="{{ route("bc.create") }}" > <i class="fas fa-truck-moving"></i> Bon de Commande</a>
                </div>
                <div class="col-md-4">
                    <a href="{{ route('bl.create') }}" > <i class="fas fa-truck-moving"></i> Bon de Livraison</a>
                </div>
                <div class="col-md-4">
                    <a href="{{ route('provider.index') }}" ><i class="fas fa-list-ul"></i>  List des Fournisseurs  </a>
                </div>
                <div class="col-md-4">
                    <a href="{{ route('provider.create') }}" ><i class="fas fa-plus"></i>  Ajouté un nouveau Fournisseurs  </a>
                </div>
                <div class="col-md-4">
                    <a href="{{ route('intermediate.create') }}" ><i class="fas fa-plus"></i>  Ajouté un intermédiaire  </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/provider/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container page-cleint-historique">
        <div class="row">
            <div class="col-md-4">
                <table>
                    <tr class="mb-4">
                        <td style="padding: 10px 0;">Compte Fournisseur</td>
                        <td><span class="span_designed"><b>{{ $provider->account }}</b></span></td>
                    </tr>
                    <tr>
                        <td style="padding: 10px 0;">Raison Sociale</td>
                        <td><span class="span_designed"><b>{{ $provider->name }}</b></span></td>
                    </tr>
                    <tr>
                        <td style="padding: 10px 0;">Gérant</td>
                        <td><span class="span_designed"><b>{{ $provider->speaker }}</b></span></td>
                    </tr>
                    <tr>
                        <td colspan="2"><br><br><br></td>
                    </tr>
                    <tr>
                        <td style="padding: 10px 0;">Chiffre d'affaire</td>
                        <td><span class="span_designed"><b>{{ $provider->turnover }} MAD</b></span></td>
                    </tr>
                    <tr>
                        <td style="padding: 10px 0;">Bénéfice</td>
                        <td><span class="span_designed"><b>?? MAD</b></span></td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <table class="table table-no-border table-date-filter">
                    <tr>
                        <td>De</td>
                        <td><input type="date"></td>
                    </tr>
                    <tr>
                        <td>A</td>
                        <td>
                            <input type="date">
                            <button class="btn-search-filterr" type="button"><i class="fas fa-search"></i></button>
                        </td>
                    </tr>
                </table>
            </div>
            @isset($products["total"])
                <div class="col-md-4">
                    <div class="float-right">
                        <table class="table table-bordered" style="max-width: 250px;">
                            <thead>
                            <tr>
                                <th>QT</th>
                                <th>Retenu</th>
                                <th style="min-width: 150px">Prix</th>
                            </tr>
                            </thead>
                            <tr>
                                <td><b>3KG</b></td>
                                <td><span class="span_designed">{{ $products['3kg']['qt'] }}</span></td>
                                <td><span class="span_designed">{{ $products['3kg']['ttc'] }} MAD</span></td>
                            </tr>
                            <tr>
                                <td><b>6KG</b></td>
                                <td><span class="span_designed">{{ $products['6kg']['qt'] }}</span></td>
                                <td><span class="span_designed">{{ $products['6kg']['ttc'] }} MAD</span></td>
                            </tr>
                            <tr>
                                <td><b>12KG</b></td>
                                <td><span class="span_designed">{{ $products['12kg']['qt'] }}</span></td>
                                <td><span class="span_designed">{{ $products['12kg']['ttc'] }} MAD</span></td>
                            </tr>
                            <tr>
                                <td><b>35KG</b></td>
                                <td><span class="span_designed">{{ $products['35kg']['qt'] }}</span></td>
                                <td><span class="span_designed">{{ $products['35kg']['ttc'] }} MAD</span></td>
                            </tr>
                            <tr>
                                <td colspan="2"><b>TOTAL</b></td>
                                <td><span class="span_designed">{{ $products['total'] }} MAD</span></td>
                            </tr>
                        </table>

                    </div>

                </div>
            @endisset
        </div>
        <div class="btn btn-lg btn-solde">Solde <span>{!! $provider->sold !!}</span></div>
        <br>
        <table id="example" class="display dataTables_wrapper" style="width:100%">
            <thead>
            <tr>
                <th>Date</th>
                <th>Intermédiaire</th>
                <th>Libellé</th>
                <th>Détails</th>
                <th>QN Entre</th>
                <th>QN Sortie</th>
                <th>Débit</th>
                <th>Crédit</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($provider->trades[0]))
                @foreach($provider->trades as $trade)
                    @if($trade->bc)
                        @foreach($trade->bc->orders as $order)
                            <tr>
                                <td>{{ \Carbon\Carbon::parse($trade->created_at)->format('d / m / y') }}</td>
                                <td>{{ $trade->bc->intermediate->name }}</td>
                                <td>BC {{ $order->product->name }} n° {{ $trade->bc->nbr }}</td>
                                <td>{{ $order->product->bottle_size }}</td>
                                <td>{{ ($order->product->name == 'consigne') ? '' : $order->qt }}</td>
                                <td></td>
                                <td>{{ $order->ht }}</td>
                                <td></td>
                            </tr>
                        @endforeach
                    @endif
                    @if($trade->bl)
                        @foreach($trade->bl->orders as $order)
                            <tr>
                                <td>{{ \Carbon\Carbon::parse($trade->created_at)->format('d / m / y') }}</td>
                                <td>{{ $trade->bl->intermediate->name }}</td>
                                <td>BL {{ $order->product->name }} n° {{ $trade->bl->nbr }}</td>
                                <td>{{ $order->product->bottle_size }}</td>
                                <td></td>
                                <td>{{ $order->qt }}</td>
                                <td></td>
                                <td>{{ $order->ht }}</td>
                            </tr>
                        @endforeach
                    @endif
                @endforeach
            @else
                <tr>
                    <td class="text-center" colspan="8">Pas de transaction Pour le moment</td>
                </tr>
            @endif
            </tbody>
        </table>
    </div>
@endsection