routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register'    => false]);
Route::middleware('auth')->group(function () {
    // Home
    Route::get('/', 'HomeController@index')->name('home');
    // Users
    Route::namespace('User')->group(function (){
        Route::get('psw','PswController@edit')->name('psw.edit');
        Route::put('psw','PswController@update')->name('psw.update');

        Route::resource('staff','StaffController')->except(['show']);
        Route::patch('staff/{staff}/restore', 'StaffController@restore')
            ->name('staff.restore');
    });
    // Payment
    Route::namespace('Payment')->group(function (){
        // Claim
        Route::resource('provider/{provider}/claim','ClaimController')->except(['show', "edit", "update"]);
        // Debt
        Route::resource('client/{client}/debt','DebtController')->except(['destroy', 'show']);
    });
    // Provider
    Route::namespace('Provider')->group(function (){
        Route::get('provider/links',"ProviderController@links")->name("provider.links");
        Route::resource('provider',"ProviderController")->except(['destroy']);
    });
    // Client
    Route::namespace('Client')->group(function (){
        // crud Client && searches
        Route::get('client/links',"ClientController@links")->name("client.links");
        Route::get('client/all',"ClientController@all")->name('client.all');
        Route::post('client/search/city',"ClientController@searchCity")->name('client.search.city');
        Route::post('client/search/name',"ClientController@searchName")->name('client.search.name');
        Route::resource('client',"ClientController")->except(['destroy']);
    });
    // intermediate
    Route::namespace('Intermediate')->group(function (){
        Route::resource('intermediate','IntermediateController')
            ->except(['destroy', 'show']);
    });
    // saisie
    Route::get('saisie',function (){
        return view('saisie.links');
    })->name('saisie');
    //truck
    Route::namespace('Truck')->group(function (){
        // truck
        Route::resource('truck',"TruckController")->except(['destroy']);
        // charge
        Route::resource('charge','ChargeController')->only(['create', "store"]);
        // loading
        Route::resource('loading','LoadingController')->except(['destroy', "show"]);
        // unloading
        Route::resource('unloading','UnloadingController')->except(['destroy', "show"]);
        // distributeur Links
        Route::get('distributeur', function () {
            return view('distributeur.links');
        })->name('distributeur.links');
    });
    // Trade
    Route::namespace('Trade')->group(function (){
        // BC
        Route::resource('bc','BcController')->except(['destroy']);
        // BL
        Route::resource('bl',"BlController");
        // Buy && Sale
        Route::resource('trade','TradeController')->only(['create', 'store']);
    });

    // Product
    Route::namespace('Product')->group(function (){
        Route::resource('price','PricesController')->only(['create', 'store']);
        Route::get('discount',"DiscountController@client")->name("discount.client");
        Route::resource('client/{client}/discount','DiscountController')->only(['create', 'store']);
    });



    // todo :: Debt Client, a_term
    // todo :: Claim Provider, a_term
    // todo:: Notification page
    // todo:: Factures liste imprimé recherche => 12

    // todo:: code barre 3d
    // todo :: Accounts  => 13

    // todo:: request and authorize => 14

    // todo :: GPS => 15
    // todo :: server => 16

});

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Staff extends Model
{
    use SoftDeletes;

    protected $fillable = ["last_name", "first_name", "mobile", "cin", "category_id", "creator_id"];

    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . strtoupper($this->last_name);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class,'creator_id');
    }

    public function owner()
    {
        return $this->hasOne(User::class,'staff_id');
    }

    public function driver()
    {
        return $this->hasMany(Driver::class,'driver_id');
    }

    public function assistant()
    {
        return $this->hasMany(Assistant::class,'assistant_id');
    }

}

app/Http/Controllers/Truck/ChargeController.php
<?php

namespace App\Http\Controllers\Truck;

use App\Charge;
use App\ChargeTruck;
use App\Http\Controllers\Controller;
use App\Http\Requests\Truck\ChargeTruckRequest;
use App\Payment;
use App\Trade;
use App\Truck;

class ChargeController extends Controller
{

    private $trades = [];

    public function create()
    {
        $charges = Charge::all();
        $trucks  = Truck::all();
        return view('charge.create',compact('trucks',"charges"));
    }

    public function store(ChargeTruckRequest $request)
    {
        // in trade
        foreach ($request->truck as $key => $truck) {
            // add trade
            $trade = Trade::create([
                "trade"             => 4,
                "ht"                => 0,
                "tva"               => 0,
                "ttc"               => 0,
                "partner_id"        => 2,
                "creator_id"        => auth()->id(),
            ]);
            $this->trades[] = $trade->id;
            // create charge truck
            ChargeTruck::create([
                "truck_id"      => $truck,
                "charge_id"     => $request->charge[$key],
                "trade_id"      => $trade->id,
                "label"         => $request->label[$key],
                "creator_id"    => auth()->id()
            ]);
            // add payments
            if($request->transfer){
                $t = Payment::create([
                    "price"             => $request->transfer,
                    "nbr_operation"     => $request->nbr_operation,
                    "mode_id"           => 3
                ]);
                foreach ($this->trades as $trade) {
                    $t->trades()->attach($trade);
                }
            }

            if($request->cheque){
                $t = Payment::create([
                    "price"             => $request->cheque,
                    "nbr_operation"     => $request->nbr_cheque,
                    "mode_id"           => 1
                ]);
                foreach ($this->trades as $trade) {
                    $t->trades()->attach($trade);
                }
            }

            if($request->a_term){
                $t = Payment::create([
                    "price"             => $request->a_term,
                    "mode_id"           => 4
                ]);
                foreach ($this->trades as $trade) {
                    $t->trades()->attach($trade);
                }
            }

        }
        session()->flash('success',"Votre Transaction a bien été ajouté");
        return back();
    }
}

app/Http/Controllers/Truck/LoadingController.php
<?php

namespace App\Http\Controllers\Truck;

use App\Http\Controllers\Controller;
use App\Http\Requests\Truck\LoadingRequest;
use App\Loading;
use App\Partner;
use App\Payment;
use App\Product;
use App\Truck;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class LoadingController extends Controller
{
    public function index()
    {
        $loadings = Loading::all();
        return view('loading.index',compact('loadings'));
    }

    public function create()
    {
        $trucks = Truck::where('transporter', false)->get();
        $gazes = Product::where('name', 'Gaz')->get();
        $providers = Partner::where('provider', 1)->get();
        return view('loading.create',compact('trucks','providers','gazes'));
    }

    public function store(Request $request)
    {
        // validation Gaze
        $valide = null;
        foreach ($request->gaz as $key => $qt) {
            if(!is_null($qt) && $qt != '0') {
                $valide = 1;
            }
        }
        if(is_null($valide)){
            return back()->withErrors(['gaz' => "votre Bon de Chargement doit avoir au moins un produit ou plus"])
                ->withInput();
        }
        $provider = Partner::find($request->provider);
        if (is_null($provider)) {
            return back()->withErrors(['provider' => "Veuillez Choisir une marque de produit valide"])
                ->withInput();
        }
        // payment
        $payment_id = null;
        if($request->cash){
            $payment = Payment::create([
                "price"     => $request->cash,
                "mode_id"   => 2
            ]);
            $truck = Truck::find($request->truck);
            $truck->update([
               "cash"   => $truck->cash + $request->cash
            ]);
            $payment_id = $payment->id;
        }
        // create new loading
        $loading = Loading::create([
            "truck_id"      => $request->truck,
            "creator_id"    => auth()->id(),
            'partner_id'    => $provider->id,
            'payment_id'    => $payment_id
        ]);
        // create new Tmp
        foreach ($request->gaz as $key => $qt) {
            if(!is_null($qt) && $qt != "0") {
                $product_gaz = Product::find($key);
                $product_consign = Product::where([
                    ['bottle_size',$product_gaz->bottle_size],
                    ['name', Str::slug('consign_' . $provider->name,'_','fr_FR')]
                ])->first();
                $loading->tmps()->create([
                    "qt"            => $qt,
                    "product_id"    => $product_gaz->id
                ]);
                $loading->tmps()->create([
                    "qt"            => $qt,
                    "product_id"    => $product_consign->id
                ]);
            }
        }
        session()->flash('success', "success");
        return redirect()->route('distributeur.links');
    }

    public function edit(Loading $loading)
    {
        $trucks = Truck::where('transporter', false)->get();
        $gazes = Product::where('name', 'Gaz')->get();
        $providers = Partner::where('provider', 1)->get();
        foreach ($gazes as $gaze) {
            if($tmp = $loading->tmps()->where('product_id',$gaze->id)->first()){
                $gaze->qt = $tmp->qt;
            }
        }
        $price = null;
        if ($payment = $loading->payment){
            $price = $payment->price;
        }
        return view('loading.edit',compact("loading", "trucks", "gazes", "providers", "price"));
    }

    public function update(Request $request, Loading $loading)
    {
        $payment = null;
        $truck = Truck::find($request->truck);
        // update payment
            // if has payment && payment not null
        if($loading->payment && !is_null($request->cash)){
            $loading->truck->update([
                "cash"  => $loading->truck - $loading->payment->price
            ]);
            $loading->payment->update(['price' => $request->cash]);
            $truck->update([
                "cash"  => $loading->payment->price + $request->cash
            ]);
        }
            // if not has payment && payment not null
        elseif(!$loading->payment && !is_null($request->cash)){
            $payment = Payment::create(['mode_id' => 2,"price" => $request->cash]);
            $loading->update([
                'payment_id'    => $payment->id
            ]);
            $truck->update([
                "cash"  => $truck->cash + $request->cash
            ]);
        }
            // if has payment && payment null
        elseif($loading->payment && is_null($request->cash)){
            $loading->truck->update([
                "cash"  => $loading->truck->cash - $loading->payment->price
            ]);
            $loading->payment->delete();
            $loading->update([
                'payment_id'    => null
            ]);
        }
        // update loading
        $provider = Partner::find($request->provider);
        $loading->update([
            "truck_id"      => $request->truck,
            'partner_id'    => $provider->id,
        ]);
        // delete tmp
        foreach ($loading->tmps as $tmp) {
            $tmp->delete();
        }
        // create tmp
        foreach ($request->gaz as $key => $qt) {
            if(!is_null($qt)) {
                $product_gaz = Product::find($key);
                $product_consign = Product::where([
                    ['bottle_size',$product_gaz->bottle_size],
                    ['name', Str::slug('consign_' . $provider->name,'_','fr_FR')]
                ])->first();
                $loading->tmps()->create([
                    "qt"            => $qt,
                    "product_id"    => $product_gaz->id
                ]);
                $loading->tmps()->create([
                    "qt"            => $qt,
                    "product_id"    => $product_consign->id
                ]);
            }
        }
        return redirect()->route('loading.edit',compact('loading'));
    }

    // TODO :: update valides loading (touch stock).
    public function updateValide(Request $request, Loading $loading)
    {
        // delete payment
        $loading->payment->delete();
        $loading->update(['payment_id' => null]);
        // delete tmp
        foreach ($loading->tmps as $tmp) {
            // todo :: touch stock
        }
        $loading->tmps();
        // update loading
        // create tmp
    }
}

app/Http/Controllers/Truck/TruckController.php
<?php

namespace App\Http\Controllers\Truck;

use App\Assistant;
use App\Category;
use App\Driver;
use App\Http\Controllers\Controller;
use App\Http\Requests\Truck\TruckRequest;
use App\Product;
use App\Truck;

class TruckController extends Controller
{
    public function index()
    {
        $trucks = Truck::all();
        return view('truck.index',compact('trucks'));
    }

    public function create()
    {
        $drivers = Category::where('category','Chauffeur')->first()->staffs;
        $assistants = Category::where('category','Assistant')->first()->staffs;

        return view('truck.create',compact('drivers', 'assistants'));
    }

    public function store(TruckRequest $request,Truck $truck,Product $product)
    {
        $request->request->add(['creator_id' => auth()->id()]);
        $truck->onCreate($request->all([
            "registered", "transporter", "creator_id", "assistant", "driver", "visit_technique","assurance"
        ]),$product);
        session()->flash('success', "Un nouveau Transport a bien été Ajouter");
        return redirect()->route('truck.show',compact('truck'));
    }

    public function show(Truck $truck)
    {
        $driver = null;
        $assistant = null;
        if($t = Driver::where([
            ['to', null],
            ['truck_id', $truck->id]
        ])->first()){
            $driver = $t->driver->full_name;
        }
        if($t = Assistant::where([
            ['to', null],
            ['truck_id', $truck->id]
        ])->first()){
            $assistant = $t->assistant->full_name;
        }
        // todo:: list of charges
        return view('truck.show',compact('truck','driver','assistant'));
    }

    public function edit(Truck $truck)
    {
        $drivers = Category::where('category','Chauffeur')->first()->staffs;
        $assistants = Category::where('category','Assistant')->first()->staffs;
        $current_assistant = Assistant::where([
            ['to', null],
            ['truck_id', $truck->id]
        ])->first();
        $current_driver = Driver::where([
            ['to', null],
            ['truck_id', $truck->id]
        ])->first();
        return view('truck.edit',compact('truck',"current_assistant","current_driver","drivers","assistants"));
    }

    public function update(TruckRequest $request, Truck $truck)
    {
        $truck->update($request->all(['registered', 'transporter', "assurance", "visit_technique"]));
        if($t = Driver::where([
            ['to', null],
            ['truck_id', $truck->id]
        ])->first()){
            $t->update(['to' => now()]);
        }
        Driver::create([
            'driver_id' =>  $request->driver,
            'from' => now(),
            'truck_id' =>  $truck->id
        ]);
        if($t = Assistant::where([
            ['to', null],
            ['truck_id', $truck->id]
        ])->first()){
            $t->update(['to' => now()]);
        }
        Assistant::create([
            'assistant_id' =>  $request->assistant,
            'from' => now(),
            'truck_id' =>  $truck->id
        ]);

        session()->flash('success', "Le Transport a bien été Mis à jour");
        return redirect()->route('truck.show',compact('truck'));
    }
}

resources/views/truck/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content container-fluid">
        <form action="{{ route('truck.store') }}" method="POST">
            <div class="row">
                @csrf
                <div class="col-md-6 offset-3">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="registered">n° d'imatrucle</label>
                            <input type="text" name="registered" id="registered" value="{{ old('registered') }}"
                                   placeholder="n° d'imatrucle" class="form-control">
                            @if($errors->has('registered'))
                                <span class="text-danger">{{ $errors->first('registered') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="transporter">Transport</label>
                            <select name="transporter" id="transporter" class="form-control">
                                <option value="0" {{ (old('transporter') == '0') ? "selected" : "" }} >Distributeur
                                </option>
                                <option value="1" {{ (old('transporter') == '1') ? "selected" : "" }} >Transporteur
                                </option>
                            </select>
                            @if($errors->has('transporter'))
                                <span class="text-danger">{{ $errors->first('transporter') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="assistant">Assistant : </label>
                            <select name="assistant" id="assistant" class="form-control">
                                @foreach($assistants as $assistant)
                                    <option value="{{ $assistant->id }}">{{ $assistant->full_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('assistant'))
                                <span class="text-danger">{{ $errors->first('assistant') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="driver">Driver : </label>
                            <select name="driver" id="driver" class="form-control">
                                @foreach($drivers as $driver)
                                    <option value="{{ $driver->id }}">{{ $driver->full_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('driver'))
                                <span class="text-danger">{{ $errors->first('driver') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="assurance">Date d'expiration Assurance :</label>
                            <input type="date" name="assurance" id="assurance" value="{{ old('assurance') }}" placeholder="Date d'expiration Assurance :" class="form-control">
                        @if($errors->has('assurance'))
                            <span class="text-danger">{{ $errors->first('assurance') }}</span>
                        @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="visit_technique">visite technique :</label>
                            <input type="date" name="visit_technique" id="visit_technique" value="{{ old('visit_technique') }}" placeholder="visite technique :" class="form-control">
                        @if($errors->has('visit_technique'))
                            <span class="text-danger">{{ $errors->first('visit_technique') }}</span>
                        @endif
                        </div>
                    </div>
                    <div class="col-md-6 offset-6 text-right">
                        <button type="submit" class="btn btn-primary">Créer</button>
                    </div>
                </div>

            </div>
        </form>
    </div>
@stop

resources/views/truck/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="content container-fluid">
        <form action="{{ route('truck.update',compact('truck')) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-6 offset-3">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="registered">n° d'imatrucle</label>
                            <input type="text" name="registered" id="registered"
                                   value="{{ (old('registered')) ?? $truck->registered }}"
                                   placeholder="n° d'imatrucle" class="form-control">
                            @if($errors->has('registered'))
                                <span class="text-danger">{{ $errors->first('registered') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="transporter">Transport</label>
                            <select name="transporter" id="transporter" class="form-control">
                                <option value="0"
                                        @if(old('transporter') == '0')
                                        selected
                                        @elseif($truck->transporter)
                                        selected
                                        @endif
                                >Distributeur
                                </option>
                                <option value="1"
                                        @if(old('transporter') == '1')
                                        selected
                                        @elseif($truck->transporter)
                                        selected
                                        @endif>Transporteur
                                </option>
                            </select>
                            @if($errors->has('transporter'))
                                <span class="text-danger">{{ $errors->first('transporter') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="assistant">Assistant : </label>
                            <select name="assistant" id="assistant" class="form-control">
                                @foreach($assistants as $assistant)
                                    <option value="{{ $assistant->id }}"
                                    @if($current_assistant->assistant_id == $assistant->id)
                                        selected
                                            @endif
                                    >{{ $assistant->full_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('assistant'))
                                <span class="text-danger">{{ $errors->first('assistant') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="driver">Driver : </label>
                            <select name="driver" id="driver" class="form-control">
                                @foreach($drivers as $driver)
                                    <option value="{{ $driver->id }}"
                                            @if($current_driver->driver_id == $driver->id)
                                            selected
                                            @endif
                                    >{{ $driver->full_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('driver'))
                                <span class="text-danger">{{ $errors->first('driver') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="assurance">Date d'expiration Assurance :</label>
                            <input type="date" name="assurance" id="assurance" value="{{ (old('assurance')) ?? $truck->assurance }}" placeholder="Date d'expiration Assurance :" class="form-control">
                            @if($errors->has('assurance'))
                                <span class="text-danger">{{ $errors->first('assurance') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="visit_technique">visite technique :</label>
                            <input type="date" name="visit_technique" id="visit_technique" value="{{ (old('visit_technique')) ?? $truck->visit_technique }}" placeholder="visite technique :" class="form-control">
                            @if($errors->has('visit_technique'))
                                <span class="text-danger">{{ $errors->first('visit_technique') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6 offset-6 text-right">
                        <button type="submit" class="btn btn-primary">Modifier</button>
                    </div>
                </div>

            </div>
        </form>
    </div>
@stop

resources/views/truck/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-6 offset-6 text-right">
                    <a href="{{ route('truck.create') }}" class="btn btn-primary">Créer un nouveau transport</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul>
                    @foreach($trucks as $truck)
                        <li>{{ $truck->registered }} <a href="{{ route('truck.show',compact('truck')) }}">Show</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@stop

resources/views/truck/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-6 offset-6 text-right">
                    <a href="{{ route('truck.edit',compact('truck')) }}" class="btn btn-primary">edit</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                Choffeur : {{ ($driver) ?? "Pas de Choffeur" }} <br>
                assistant : {{ ($assistant) ?? "Pas de d'assistant" }}<br>
                Type: {{ ($truck->transporter) ? 'Transporteur' : 'Distributeur' }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                liste des charges :
            </div>
        </div>
    </div>
@stop