routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register'    => false]);
Route::middleware('auth')->group(function () {
    // Home
    Route::get('/', 'HomeController@index')->name('home');
    // Users
    Route::namespace('User')->group(function (){
        Route::get('psw','PswController@edit')->name('psw.edit');
        Route::put('psw','PswController@update')->name('psw.update');

        Route::resource('staff','StaffController')->except(['show']);
        Route::patch('staff/{staff}/restore', 'StaffController@restore')
            ->name('staff.restore');
    });
    // Payment
    Route::namespace('Payment')->group(function (){
        // Claim
        Route::resource('provider/{provider}/claim','ClaimController')->except(['show', "edit", "update"]);
        // Debt
        Route::resource('client/{client}/debt','DebtController')->except(['destroy', 'show']);
    });
    // Provider
    Route::namespace('Provider')->group(function (){
        Route::get('provider/links',"ProviderController@links")->name("provider.links");
        Route::resource('provider',"ProviderController")->except(['destroy']);
    });
    // Client
    Route::namespace('Client')->group(function (){
        // crud Client && searches
        Route::get('client/links',"ClientController@links")->name("client.links");
        Route::get('client/all',"ClientController@all")->name('client.all');
        Route::post('client/search/city',"ClientController@searchCity")->name('client.search.city');
        Route::post('client/search/name',"ClientController@searchName")->name('client.search.name');
        Route::resource('client',"ClientController")->except(['destroy']);
    });
    // intermediate
    Route::namespace('Intermediate')->group(function (){
        Route::resource('intermediate','IntermediateController')
            ->except(['destroy', 'show']);
    });
    // saisie
    Route::get('saisie',function (){
        return view('saisie.links');
    })->name('saisie');
    //truck
    Route::namespace('Truck')->group(function (){
        // truck
        Route::resource('truck',"TruckController")->except(['destroy']);
        // charge
        Route::resource('charge','ChargeController')->only(['create', "store"]);
        // loading
        Route::resource('loading','LoadingController')->except(['destroy', "show"]);
        // unloading
        Route::resource('unloading','UnloadingController')->except(['destroy', "show"]);
        // distributeur Links
        Route::get('distributeur', function () {
            return view('distributeur.links');
        })->name('distributeur.links');
    });
    // Trade
    Route::namespace('Trade')->group(function (){
        // BC
        Route::resource('bc','BcController')->except(['destroy']);
        // BL
        Route::resource('bl',"BlController");
        // Buy && Sale
        Route::resource('trade','TradeController')->only(['create', 'store']);
    });

    // Product
    Route::namespace('Product')->group(function (){
        Route::resource('price','PricesController')->only(['create', 'store']);
        Route::get('discount',"DiscountController@client")->name("discount.client");
        Route::resource('client/{client}/discount','DiscountController')->only(['create', 'store']);
    });



    // todo :: Debt Client, a_term
    // todo :: Claim Provider, a_term
    // todo:: Notification page
    // todo:: Factures liste imprimé recherche => 12

    // todo:: code barre 3d
    // todo :: Accounts  => 13

    // todo:: request and authorize => 14

    // todo :: GPS => 15
    // todo :: server => 16

});

app/Unloading.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unloading extends Model
{
    protected $fillable = ["truck_id", "creator_id", "partner_id"];

    public function getNbrChequeAttribute()
    {
        if($payment = $this->payments()->where('mode_id',1)->first()){
            return $payment->nbr_operation;
        }
        return null;
    }
    public function getChequeAttribute()
    {
        if($payment = $this->payments()->where('mode_id',1)->first()){
            return $payment->price;
        }
        return null;
    }
    public function getCashAttribute()
    {
        if($payment = $this->payments()->where('mode_id',2)->first()){
            return $payment->price;
        }
        return null;
    }
    public function creator()
    {
        return $this->belongsTo(User::class, 'creator_id');
    }

    public function truck()
    {
        return $this->belongsTo(Truck::class);
    }

    public function partner()
    {
        return $this->belongsTo(Partner::class);
    }
    // payment many to many => get with sum
    public function payments()
    {
        return $this->belongsToMany(Payment::class,"payment_unloading");
    }

    public function tmps()
    {
        return $this->hasMany(Tmp::class);
    }

}

app/Http/Controllers/Truck/UnloadingController.php
<?php

namespace App\Http\Controllers\Truck;

use App\Http\Controllers\Controller;
use App\Partner;
use App\Payment;
use App\Product;
use App\Stock;
use App\Truck;
use App\Unloading;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class UnloadingController extends Controller
{

    public function index()
    {
        $unloadings = Unloading::all();
        return view('unloading.index',compact('unloadings'));
    }

    public function create()
    {
        $trucks = Truck::where('transporter', false)->get();
        $providers = Partner::where('provider', 1)->get();
        $gazes = Product::where('name', 'Gaz')->get();
        $etrangers = Product::where('name', 'E Tranger')->get();
        $defecteusees = [];
        $consignees = [];
        foreach ($providers as $provider) {
            $consignees[$provider->id] = Product::where('name', Str::slug('consign ' . $provider->name, '_', 'fr_FR'))->get();
            $defecteusees[$provider->id] = Product::where('name', Str::slug('defecteuse ' . $provider->name, '_', 'fr_FR'))->get();
        }
        return view('unloading.create', compact("trucks", "providers", "gazes", "etrangers", "defecteusees", "consignees"));
    }

    public function store(Request $request)
    {
        // create unloading
        $unloading = Unloading::create([
            "truck_id" => $request->truck, "creator_id" => auth()->id(), "partner_id" => $request->provider
        ]);
        // create payment
        $this->addPayment($request,$unloading);
        // tmp
        $this->storeTmp($request, $unloading);
        session()->flash('success', "success");
        return redirect()->route('distributeur.links');
    }

    private function storeTmp($request, Unloading $unloading)
    {
        $provider = Partner::find($request->provider);

        foreach ($request->gaz as $key => $qt) {
            if (!is_null($qt) && $qt != 0) {
                $product_gaz = Product::find($key);
                $product_consign = Product::where([
                    ['bottle_size', $product_gaz->bottle_size],
                    ['name', Str::slug('consign_' . $provider->name, '_', 'fr_FR')]
                ])->first();
                $unloading->tmps()->create([
                    "qt" => $qt, "product_id" => $product_gaz->id
                ]);
                $unloading->tmps()->create([
                    "qt" => $qt, "product_id" => $product_consign->id
                ]);
                // unload from truck
                // load to store
                $truck_stock_gaz = Stock::where([
                    ['product_id', $product_gaz->id], ['truck_id', $request->truck]
                ])->first();
                $truck_stock_gaz->update([
                    "qt" => $truck_stock_gaz->qt - $qt
                ]);
                $truck_stock_consign = Stock::where([
                    ['product_id', $product_consign->id], ['truck_id', $request->truck]
                ])->first();
                $truck_stock_consign->update([
                    "qt" => $truck_stock_consign->qt - $qt
                ]);
                $store_stock_gaz = Stock::where([
                    ['product_id', $product_gaz->id], ['store_id', 1]
                ])->first();
                $store_stock_gaz->update([
                    "qt" => $store_stock_gaz->qt + $qt
                ]);
                $store_stock_consign = Stock::where([
                    ['product_id', $product_consign->id], ['store_id', 1]
                ])->first();
                $store_stock_consign->update([
                    "qt" => $store_stock_consign->qt + $qt
                ]);
            }
        }

        foreach ($request->defecteuse as $key => $qt) {
            $this->addStoreTmp($key, $qt, $unloading, $request->truck);
        }

        foreach ($request->etranger as $key => $qt) {
            $this->addStoreTmp($key, $qt, $unloading, $request->truck);
        }

        foreach ($request->consign as $key => $qt) {
            $this->addStoreTmp($key, $qt, $unloading, $request->truck);
        }

    }

    public function addPayment($request,Unloading $unloading)
    {
        $payment = [];
        $truck = Truck::find($request->truck);
        $cash = $truck->cash;
        $cheque = $truck->cheque;
        if ($request->cheque) {
            $cheque = Payment::create([
                "price" => $request->cheque, "nbr_operation" => $request->nbr_cheque, "mode_id" => 1
            ]);
            $payment[] = $cheque->id;
            $cheque = $cheque + $cheque->price;
        }
        if ($request->cash) {
            $cash = Payment::create([
                "price" => $request->cash, "mode_id" => 2
            ]);
            $payment[] = $cash->id;
            $cash = $cash + $cash->price;
        }
        if(isset($payment[0])){
            $unloading->payments()->attach($payment);
            $truck->update([
                "cash"      => $cash,
                "cheque"    => $cheque
            ]);
        }
    }

    private function addStoreTmp($key, $qt, $unloading, $truck_id)
    {
        if (!is_null($qt) && $qt != 0) {
            $product = Product::find($key);
            $unloading->tmps()->create([
                "qt" => $qt, "product_id" => $product->id
            ]);
            $truck_stock = Stock::where([
                ['product_id', $product->id], ['truck_id', $truck_id]
            ])->first();
            $store_stock = Stock::where([
                ['product_id', $product->id], ['store_id', 1]
            ])->first();
            $truck_stock->update([
                "qt" => $truck_stock->qt - $qt
            ]);
            $store_stock->update([
                "qt" => $store_stock->qt - $qt
            ]);
        }
    }

    public function edit(Unloading $unloading)
    {
        $trucks = Truck::where('transporter', false)->get();
        $providers = Partner::where('provider', 1)->get();
        $gazes = Product::where('name', 'Gaz')->get();
        foreach ($gazes as $gaze) {
            if($tmp = $unloading->tmps()->where('product_id',$gaze->id)->first()){
                $gaze->qt = $tmp->qt;
            }
        }

        $etrangers = Product::where('name', 'E Tranger')->get();
        foreach ($etrangers as $etranger) {
            if($tmp = $unloading->tmps()->where('product_id',$etranger->id)->first()){
                $etranger->qt = $tmp->qt;
            }
        }

        $consignees = [];
        $defecteusees = [];

        foreach ($providers as $provider) {
            $consignes = Product::where('name', Str::slug('consign ' . $provider->name, '_', 'fr_FR'))->get();
            $defecteuses = Product::where('name', Str::slug('defecteuse ' . $provider->name, '_', 'fr_FR'))->get();
            foreach ($consignes as $product) {
                if($tmp = $unloading->tmps()->where('product_id',$product->id)->first()){
                    $product->qt = $tmp->qt;
                }
            }
            $consignees[$provider->id] = $consignes;
            foreach ($defecteuses as $product) {
                if($tmp = $unloading->tmps()->where('product_id',$product->id)->first()){
                    $product->qt = $tmp->qt;
                }
            }
            $defecteusees[$provider->id] = $defecteuses;
        }

        return view('unloading.edit', compact("unloading", "trucks", "providers", "gazes", "etrangers", "defecteusees", "consignees"));
    }

    public function update(Request $request, Unloading $unloading)
    {
        // delete payments
        $this->subPayment($unloading);
        // create payment
        $this->addPayment($request,$unloading);
        // delete tmp
        $this->subStoreTmp($unloading);
        // update loading
        $unloading->update([
            "truck_id" => $request->truck,
            "partner_id" => $request->provider
        ]);
        // create tmp
        $this->storeTmp($request, $unloading);
        session()->flash('success', "update success");
        return redirect()->route('unloading.edit',compact('unloading'));
    }

    private function subStoreTmp(Unloading $unloading)
    {
        foreach ($unloading->tmps as $tmp) {
            $stock_truck = Stock::where([
                ['product_id', $tmp->product_id],
                ['truck_id', $unloading->truck_id]
            ])->first();
            $stock_store = Stock::where([
                ['product_id', $tmp->product_id],
                ['store_id', 1]
            ])->first();
            // sub from stock store
            $stock_store->update([
                'qt'    => $stock_store->qt - $tmp->qt
            ]);
            // add to stock truck
            $stock_truck->update([
                "qt"    => $stock_truck->qt + $tmp->qt
            ]);
            // delete tmps
            $tmp->delete();
        }
    }

    public function subPayment(Unloading $unloading)
    {
        if(isset($unloading->payments[0])){
            foreach ($unloading->payments as $payment) {
                $unloading->payments()->detach([$payment->id]);
                if($payment->mode_id == 1){
                    $unloading->truck->update([
                        'cheque'  => $unloading->truck->cheque  - $payment->price
                    ]);
                }
                if ($payment->mode_id == 2) {
                    $unloading->truck->update([
                        'cash' => $unloading->truck->cash - $payment->price
                    ]);
                }
                $payment->delete();
            }
        }
    }

}

resources/views/unloading/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="bon-command-fournisseur">
            <form action="{{ route("unloading.store") }}" method="POST">
            @csrf
            <!-- provider -->
                <div style="max-width:595px;margin: 0 auto 20px;" class="text-left">
                    <b>Fournisseur :</b>
                    <select name="provider" title="Provider" id="provider" class="btn-spanen" required>
                        @foreach($providers as $provider)
                            <option value="{{ $provider->id }}">
                                {{ $provider->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <!-- transporter -->
                <div style="max-width:595px;margin: 0 auto 20px;" class="text-left">
                    <b>Distributeur :</b>
                    <select name="truck" title="Truck" class="btn-spanen" required>
                        @foreach($trucks as $truck)
                            <option value="{{ $truck->id }}">
                                {{ $truck->registered }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <!-- products -->
                <div class="row">
                    <!-- gaz -->
                    <div class="col-md-3">
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <th colspan="2" class="text-center">GAZ</th>
                            </tr>
                            </thead>
                            <thead>
                            <tr>
                                <th>Size</th>
                                <th>Quantité</th>
                            </tr>
                            </thead>
                            <tbody style="background: #7cb3b9;">
                            @foreach($gazes as $gaze)
                                <tr style="max-width: 160px !important;">
                                    <td class="text-center"><b>{{ $gaze->bottle_size }}</b></td>
                                    <td>
                                        <input type="number" min="0"
                                               name="gaz[{{ $gaze->id }}]" value="{{ old('gaz['. $gaze->id .']') }}"
                                               data-price="{{ $gaze->lastPrice()['buy'] }}"
                                               data-tva="10"
                                               data-target="#gaz_price_{{ $gaze->id }}"
                                               class="btn-spanen prices" style="max-width: 80px !important;">
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @if($errors->has('gaz'))
                            <div class="row">
                                <div class="col-xs-12">
                                    <span class="text-danger">{{ $errors->first('gaz') }}</span>
                                </div>
                            </div>
                        @endif
                    </div>
                    <!-- etranger -->
                    <div class="col-md-3">
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <th colspan="2" class="text-center">Etranger</th>
                            </tr>
                            </thead>
                            <thead>
                            <tr>
                                <th>Size</th>
                                <th>Quantité</th>
                            </tr>
                            </thead>
                            <tbody style="background: #7cb3b9;">
                            @foreach($etrangers as $etranger)
                                <tr style="max-width: 160px !important;">
                                    <td class="text-center"><b>{{ $etranger->bottle_size }}</b></td>
                                    <td>
                                        <input type="number" min="0"
                                               name="etranger[{{ $etranger->id }}]"
                                               value="{{ old('etranger['. $etranger->id .']') }}"
                                               data-price="{{ $etranger->lastPrice()['buy'] }}"
                                               data-tva="10"
                                               data-target="#etranger_price_{{ $etranger->id }}"
                                               class="btn-spanen prices" style="max-width: 80px !important;">
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @if($errors->has('etranger'))
                            <div class="row">
                                <div class="col-xs-12">
                                    <span class="text-danger">{{ $errors->first('etranger') }}</span>
                                </div>
                            </div>
                        @endif
                    </div>
                    <!-- consign -->
                    @foreach($consignees as $key => $consignee)
                        <div class="col-md-3 consign" id="consign_{{ $key }}">
                            <table class="table table-bordered text-center">
                                <thead>
                                <tr>
                                    <th colspan="2"
                                        class="text-center">{{ str_replace('_',' ',strtoupper($consignees[$key][0]->name))  }}</th>
                                </tr>
                                </thead>
                                <thead>

                                <tr>
                                    <th>Size</th>
                                    <th>Quantité</th>
                                </tr>
                                </thead>
                                <tbody style="background: #7cb3b9;">
                                @foreach($consignee as $consign)
                                    <tr style="max-width: 160px !important;">
                                        <td class="text-center"><b>{{ $consign->bottle_size }}</b></td>
                                        <td>
                                            <input type="number" min="0"
                                                   name="consign[{{ $consign->id }}]"
                                                   value="{{ old('consign['. $consign->id .']') }}"
                                                   data-price="{{ $consign->lastPrice()['buy'] }}"
                                                   data-tva="20"
                                                   data-target="#consign_price_{{ $consign->id }}"
                                                   class="btn-spanen qt_consign prices"
                                                   style="max-width: 80px !important;">
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                @endforeach
                    <!-- consign -->
                    @foreach($defecteusees as $key => $defecteuses)
                        <div class="col-md-3 consign" id="def_{{ $key }}">
                            <table class="table table-bordered text-center">
                                <thead>
                                <tr>
                                    <th colspan="2"
                                        class="text-center">{{ str_replace('_',' ',strtoupper($defecteusees[$key][0]->name))  }}</th>
                                </tr>
                                </thead>
                                <thead>
                                <tr>
                                    <th>Size</th>
                                    <th>Quantité</th>
                                </tr>
                                </thead>
                                <tbody style="background: #7cb3b9;">
                                @foreach($defecteuses as $defecteuse)
                                    <tr style="max-width: 160px !important;">
                                        <td class="text-center"><b>{{ $defecteuse->bottle_size }}</b></td>
                                        <td>
                                            <input type="number" min="0"
                                                   name="defecteuse[{{ $defecteuse->id }}]"
                                                   value="{{ old('defecteuse['. $defecteuse->id .']') }}"
                                                   data-price="{{ $defecteuse->lastPrice()['buy'] }}"
                                                   data-tva="20"
                                                   data-target="#defecteuse_price_{{ $defecteuse->id }}"
                                                   class="btn-spanen qt_consign prices"
                                                   style="max-width: 80px !important;">
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                @endforeach

                </div>
                <!-- Submit -->
                <div class="row mt-5">
                    <div class="col-md-6 text-left">
                        <h5 class="mode_paiement_title">Mode de Paiement </h5>
                        <table>
                            <tr>
                                <td><h5>Chéque </h5></td>
                                <td><input type="number" name="cheque" value="{{ old('cheque') }}"
                                           placeholder="montant" class="btn-spanen">
                                    <input type="number" name="nbr_cheque" value="{{ old('nbr_cheque') }}"
                                           placeholder="numéro de chéque"
                                           class="btn-spanen">
                                </td>
                            </tr>
                            @if($errors->has('cheque'))
                                <tr>
                                    <td colspan="2">
                                        <span class="text-danger">{{ $errors->first('cheque') }}</span>
                                    </td>
                                </tr>
                            @endif
                            @if($errors->has('nbr_cheque'))
                                <tr>
                                    <td colspan="2">
                                        <span class="text-danger">{{ $errors->first('nbr_cheque') }}</span>
                                    </td>
                                </tr>
                            @endif
                            <tr>
                                <td><h5>cash </h5></td>
                                <td>
                                    <input type="number" name="cash" value="{{ old('cash') }}"
                                           placeholder="cash" class="btn-spanen">
                                </td>
                            </tr>
                            @if($errors->has('cash'))
                                <tr>
                                    <td colspan="2">
                                        <span class="text-danger">{{ $errors->first('cash') }}</span>
                                    </td>
                                </tr>
                            @endif
                        </table>
                    </div>
                    <div class="col-md-6">
                        <button class="btn-imprimer"><i class="fas fa-file-download"></i> Validé</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@stop

@push('scripts')
<script>
    (function () {
        function ttc() {
            var $total_ttc = 0;
            $('.total_ttc').each(function () {
                if ($(this).val().length > 0) {
                    $total_ttc = parseInt($(this).val()) + parseInt($total_ttc)
                }
            })
            $('#ttc').val($total_ttc.toFixed(2) + ' MAD')
        }

        function consign() {
            $('.consign').each(function () {
                $(this).hide();
            });
            $('.qt_consign').each(function () {
                $(this).val('');
            });
            var $provider = $('#provider').val();
            $('#consign_' + $provider).show();
            $('#def_' + $provider).show();
        }

        consign()
        ttc()
        var $body = $('body');
        $body.on('change', '#provider', function () {
            consign()
            ttc()
        })

        $body.on('change', ".prices", function () {
            var $price = $(this).attr('data-price');
            var $tva = $(this).attr('data-tva');
            var $qt = $(this).val()
            var $ht = parseInt($price * $qt)
            var $ttc = parseInt(($ht * $tva / 100) + $ht)
            var $target = $(this).attr('data-target');
            $($target).val($ttc);
            ttc()
        })
    })(jQuery)
</script>
@endpush

resources/views/unloading/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <table>
                    <thead>
                    <tr>
                        <th>Distributeur</th>
                        <th>Fournisseur</th>
                        <th>Payment</th>
                        <th>edit</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($unloadings as $unloading)
                        <tr>
                            <td>{{ $unloading->truck->registered }}</td>
                            <td>{{ $unloading->partner->name }}</td>
                            <td>{{ ($unloading->payments[0]) ? $unloading->payments()->sum('price') . ' MAD' : '0 MAD'}}</td>
                            <td>
                                <a href="{{ route('unloading.edit',compact('unloading')) }}"> EDIT</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop