routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register'    => false]);
Route::middleware('auth')->group(function () {
    // Home
    Route::get('/', 'HomeController@index')->name('home');
    // Users
    Route::namespace('User')->group(function (){
        Route::get('psw','PswController@edit')->name('psw.edit');
        Route::put('psw','PswController@update')->name('psw.update');

        Route::resource('staff','StaffController')->except(['show']);
        Route::patch('staff/{staff}/restore', 'StaffController@restore')
            ->name('staff.restore');
    });
    // Payment
    Route::namespace('Payment')->group(function (){
        // Claim
        Route::resource('provider/{provider}/claim','ClaimController')->except(['show', "edit", "update"]);
        // Debt
        Route::resource('client/{client}/debt','DebtController')->except(['destroy', 'show']);
    });
    // Provider
    Route::namespace('Provider')->group(function (){
        Route::get('provider/links',"ProviderController@links")->name("provider.links");
        Route::resource('provider',"ProviderController")->except(['destroy']);
    });
    // Client
    Route::namespace('Client')->group(function (){
        // crud Client && searches
        Route::get('client/links',"ClientController@links")->name("client.links");
        Route::get('client/all',"ClientController@all")->name('client.all');
        Route::post('client/search/city',"ClientController@searchCity")->name('client.search.city');
        Route::post('client/search/name',"ClientController@searchName")->name('client.search.name');
        Route::resource('client',"ClientController")->except(['destroy']);
    });
    // intermediate
    Route::namespace('Intermediate')->group(function (){
        Route::resource('intermediate','IntermediateController')
            ->except(['destroy', 'show']);
    });
    // saisie
    Route::get('saisie',function (){
        return view('saisie.links');
    })->name('saisie');
    //truck
    Route::namespace('Truck')->group(function (){
        // truck
        Route::resource('truck',"TruckController")->except(['destroy']);
        // charge
        Route::resource('charge','ChargeController')->only(['create', "store"]);
        // loading
        Route::resource('loading','LoadingController')->except(['destroy', "show"]);
        // unloading
        Route::resource('unloading','UnloadingController')->except(['destroy', "show"]);
        // distributeur Links
        Route::get('distributeur', function () {
            return view('distributeur.links');
        })->name('distributeur.links');
    });
    // Trade
    Route::namespace('Trade')->group(function (){
        // BC
        Route::resource('bc','BcController')->except(['destroy']);
        // BL
        Route::resource('bl',"BlController");
        // Buy && Sale
        Route::resource('trade','TradeController')->only(['create', 'store']);
    });

    // Product
    Route::namespace('Product')->group(function (){
        Route::resource('price','PricesController')->only(['create', 'store']);
        Route::get('discount',"DiscountController@client")->name("discount.client");
        Route::resource('client/{client}/discount','DiscountController')->only(['create', 'store']);
    });



    // todo :: Debt Client, a_term
    // todo :: Claim Provider, a_term
    // todo:: Notification page
    // todo:: Factures liste imprimé recherche => 12

    // todo:: code barre 3d
    // todo :: Accounts  => 13

    // todo:: request and authorize => 14

    // todo :: GPS => 15
    // todo :: server => 16

});

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Staff extends Model
{
    use SoftDeletes;

    protected $fillable = ["last_name", "first_name", "mobile", "cin", "category_id", "creator_id"];

    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . strtoupper($this->last_name);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class,'creator_id');
    }

    public function owner()
    {
        return $this->hasOne(User::class,'staff_id');
    }

    public function driver()
    {
        return $this->hasMany(Driver::class,'driver_id');
    }

    public function assistant()
    {
        return $this->hasMany(Assistant::class,'assistant_id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'name', 'password', "staff_id"
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $dates = [
        'created_at', "updated_at"
    ];

    public function getIsAdminAttribute()
    {
        return $this->staff->category->category === "Gérant";
    }

    public function staff()
    {
        return $this->belongsTo(Staff::class,'staff_id');
    }

    /**
     * Les Produits que j'ai ajouté
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function createdProducts()
    {
        return $this->hasMany(Product::class,'creator_id');
    }

    /**
     * Les Prix que j'ai ajouté
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productPrices()
    {
        return $this->hasMany(Price::class,'creator_id');
    }

    /**
     * La liste de tous les Camions Transporteurs et distributeurs
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function trucks()
    {
        return $this->hasMany(Truck::class,'creator_id');
    }

    public function partners()
    {
        return $this->hasMany(Partner::class,'creator_id');
    }

    public function staffs()
    {
        return $this->hasMany(Staff::class,'creator_id');
    }

    public function chargeTrucks()
    {
        return $this->hasMany(ChargeTruck::class);
    }

    public function chargeStores()
    {
        return $this->hasMany(ChargeStore::class,'creator_id');
    }

    public function trades()
    {
        return $this->hasMany(Trade::class,'creator_id');
    }

    public function loadings()
    {
        return $this->hasMany(Loading::class,'creator_id');
    }

    public function unloadings()
    {
        return $this->hasMany(Unloading::class,'creator_id');
    }


}

app/Http/Controllers/User/PswController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\PswRequest;
use Illuminate\Support\Facades\Hash;

class PswController extends Controller
{
    public function edit()
    {
        return view('user.psw');
    }

    public function update(PswRequest $request)
    {
        if (Hash::check($request->old_password, auth()->user()->getAuthPassword())) {
            auth()->user()->update([
                'password'  => bcrypt($request->password),
            ]);
            session()->flash('success', 'Votre a bien été Ajouté');
            return redirect()->route('home');
        }
        return back()->withErrors([
            'old_password'  => "Votre mot de passe Actuel est erroné"
        ])->withInput(['old_password']);
    }
}

app/Http/Controllers/User/StaffController.php
<?php

namespace App\Http\Controllers\User;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\StaffStoreRequest;
use App\Http\Requests\User\StaffUpdateRequest;
use App\Staff;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class StaffController extends Controller
{
    public function index()
    {
        $staffs = Staff::withTrashed()
            ->with(["owner","category"])
            ->orderBy('deleted_at',"asc")
            ->get();

        return view('user.index',compact('staffs'));
    }

    public function create()
    {
        $categories = Category::where("id", "!=", 1)->get();
        return view('user.create',compact('categories'));
    }

    public function store(StaffStoreRequest $request,Staff $staff)
    {
        $request->request->add([
            "creator_id" => auth()->id(),
            "category_id"   => $request->category
        ]);
        $staff = $staff->create($request->all([
            "last_name", "first_name", "mobile", "cin", "category_id", "creator_id"
        ]));

        if ((int) $request->category === 2 || (int) $request->category == 4) {
            $staff->owner()->create([
                "name"          => $request->name,
                "password"      => bcrypt($request->password),
                "remember_token"    => Str::random(10)
            ]);
        }

        session()->flash('success', "Une Nouvelle Personne a bien été ajouté");

        return redirect()->route('staff.index');

    }

    public function edit(Staff $staff)
    {
        return view('user.edit',compact('staff'));
    }

    public function update(StaffUpdateRequest $request, Staff $staff)
    {
        $staff->update($request->all(["last_name", "first_name", "mobile", "cin"]));
        session()->flash('success', 'Les informations de La personne a bien été modifier');
        return redirect()->route('staff.index');
    }

    public function destroy(Staff $staff)
    {
        if($staff->owner){
            $staff->owner->delete();
        }
        $staff->delete();
        session()->flash('success', "La Personne a bien été supprimé");
        return redirect()->route('staff.index');
    }

    public function restore(int $id)
    {
        $staff = Staff::withTrashed()->find($id);
        if($staff){
            $staff->restore();
            if($user = User::withTrashed()->where('staff_id',$id)->first()){
                $user->restore();
            }
            session()->flash('success', $staff->full_name . " a bien été débloquez");
            return redirect()->route('staff.index');
        }
        return abort(404);
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                    <div class="card-header">Ajouté une nouvelle Personne</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('staff.store') }}">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="last_name">Nom :</label>
                                        <input type="text" name="last_name" id="last_name"
                                               value="{{ old('last_name') }}" placeholder="Nom :" class="form-control"
                                               required>
                                        @if($errors->has('last_name'))
                                            <span class="text-danger">{{ $errors->first('last_name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="first_name">Prénom</label>
                                        <input type="text" name="first_name" id="first_name"
                                               value="{{ old('first_name') }}" placeholder="Prénom"
                                               class="form-control" required>
                                        @if($errors->has('first_name'))
                                            <span class="text-danger">{{ $errors->first('first_name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="mobile">Portable :</label>
                                        <input type="tel" name="mobile" id="mobile" value="{{ old('mobile') }}"
                                               placeholder="Portable" class="form-control">
                                        @if($errors->has('mobile'))
                                            <span class="text-danger">{{ $errors->first('mobile') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="mobile">N° de la Carte CIN</label>
                                        <input type="text" name="cin" id="cin" value="{{ old('mobile') }}"
                                               placeholder="N° de la Carte CIN" class="form-control">
                                        @if($errors->has('cin'))
                                            <span class="text-danger">{{ $errors->first('cin') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="category">Catégorie :</label>
                                        <select name="category" id="category" class="form-control" required>
                                            @foreach($categories as $category)
                                                <option value="{{ $category->id }}"
                                                        {{ (old('category') == $category->id) ? 'selected' : '' }}>
                                                    {{ $category->category }}
                                                </option>
                                            @endforeach
                                        </select>
                                        @if($errors->has('category'))
                                            <span class="text-danger">{{ $errors->first('category') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12 account">
                                    <div class="form-group">
                                        <label for="name">Nom d'utilisateur</label>
                                        <input type="text" name="name" id="name" value="{{ old('name') }}"
                                               placeholder="Nom d'utilisateur" class="form-control" >
                                        @if($errors->has('name'))
                                            <span class="text-danger">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6 account" id="account">
                                    <div class="form-group">
                                        <label for="password">Mot de passe :</label>
                                        <input type="password" name="password" id="password" placeholder="Mot de passe"
                                               class="form-control" >
                                        @if($errors->has('password'))
                                            <span class="text-danger">{{ $errors->first('password') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6 account">
                                    <div class="form-group">
                                        <label for="password_confirmation">confirmation Mot de passe :</label>
                                        <input type="password" name="password_confirmation" id="password_confirmation"
                                               placeholder="confirmation Mot de passe" class="form-control">
                                        @if($errors->has('password_confirmation'))
                                            <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" name="Créer" id="Create" value="Créer"
                                           class="btn btn-primary float-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script>
    (function () {
        function selected() {
            var category = parseInt($('#category').val())
            if (category === 2 || category === 4) {
                $('.account').show()
            } else {
                $('.account').hide()
            }
        }

        selected()
        $('body').on('change', '#category', function () {
            selected()
        })
    })(jQuery)
</script>
@endpush

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                    <div class="card-header">Mettre à jour les Informations d'utilisateur</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('staff.update',compact('staff')) }}">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="last_name">Nom :</label>
                                        <input type="text" name="last_name" id="last_name"
                                               value="{{ (old('last_name')) ?? $staff->last_name }}" placeholder="Nom :" class="form-control"
                                               required>
                                        @if($errors->has('last_name'))
                                            <span class="text-danger">{{ $errors->first('last_name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="first_name">Prénom</label>
                                        <input type="text" name="first_name" id="first_name"
                                               value="{{ (old('first_name')) ?? $staff->first_name }}" placeholder="Prénom"
                                               class="form-control"  required>
                                        @if($errors->has('first_name'))
                                            <span class="text-danger">{{ $errors->first('first_name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="mobile">Portable</label>
                                        <input type="tel" name="mobile" id="mobile"
                                               value="{{ (old('mobile')) ?? $staff->mobile }}"
                                               placeholder="Portable" class="form-control"  required>
                                        @if($errors->has('mobile'))
                                            <span class="text-danger">{{ $errors->first('mobile') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="mobile">N° de la Carte CIN</label>
                                        <input type="text" name="cin" id="cin"
                                               placeholder="N° de la Carte CIN"
                                               value="{{ (old('cin')) ?? $staff->cin }}"
                                               class="form-control">
                                        @if($errors->has('cin'))
                                            <span class="text-danger">{{ $errors->first('cin') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" name="Créer" id="Create" value="Mettre à jour"
                                           class="btn btn-primary float-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="float-right">
                    <a href="{{ route('staff.create') }}"
                       class="btn btn-success text-right"
                    >Ajouter Une nouvelle personne</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Nom et Prénom</th>
                        <th>category</th>
                        <th>Mobile</th>
                        <th>CIN</th>
                        <th class="text-center" colspan="2">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($staffs as $staff)
                        <tr>
                            <td class="text-left">{{ $staff->full_name }}</td>
                            <td>{{ $staff->category->category }}</td>
                            <td>{{ $staff->mobile }}</td>
                            <td>{{ $staff->cin }}</td>
                        
                            @if($staff->category_id !== 1)
                                @if($staff->trashed())
                                    <td colspan="2">
                                        <a href="#" class="btn btn-warning"
                                           onclick="event.preventDefault();
                                                   document.getElementById('restore-user-{{ $staff->id }}').submit();">
                                            {{ __('Réstorer') }}
                                        </a>

                                        <form id="restore-user-{{ $staff->id }}"
                                              action="{{ route('staff.restore',compact('staff')) }}"
                                              method="POST" style="display: none;">
                                            @csrf
                                            @method('PATCH')
                                        </form>
                                    </td>
                                @else
                                    <td>
                                        <a href="{{ route('staff.edit',compact('staff')) }}"
                                           class="btn btn-success">Mettre à jour</a>
                                    </td>
                                    <td>
                                        <a href="#" class="btn btn-danger" onclick="event.preventDefault();
                                                document.getElementById('delete-user-{{ $staff->id }}').submit();">
                                            {{ __('Supprimé') }}
                                        </a>

                                        <form id="delete-user-{{ $staff->id }}"
                                              action="{{ route('staff.destroy',compact('staff')) }}"
                                              method="POST" style="display: none;">
                                            @csrf
                                            @method('delete')
                                        </form>
                                    </td>
                                @endif
                            @endif
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/user/psw.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                    <div class="card-header">Mettre à jour Votre Mot de passe</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('psw.update') }}">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="old_password">Mot de passe Actuel :</label>
                                        <input type="password" name="old_password" id="old_password" placeholder="Mot de passe Actuel" class="form-control" required>
                                        @if($errors->has('old_password'))
                                            <span class="text-danger">{{ $errors->first('old_password') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="password">Mot de passe :</label>
                                        <input type="password" name="password" id="password" placeholder="Mot de passe" class="form-control" required>
                                        @if($errors->has('password'))
                                            <span class="text-danger">{{ $errors->first('password') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="password_confirmation">confirmation Mot de passe :</label>
                                        <input type="password" name="password_confirmation" id="password_confirmation"
                                               placeholder="confirmation Mot de passe" class="form-control" required>
                                        @if($errors->has('password_confirmation'))
                                            <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" name="Créer" id="Create" value="Mettre à jour"
                                           class="btn btn-primary float-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection